apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tasks
  namespace: tasks-namespace

spec:
  selector:
    matchLabels:
      app: api-tasks
  replicas: 1
  template:
    metadata:
      labels:
        app: api-tasks
    spec:
      
      containers:
        - name: api-tasks
          image: loliconario69/laravel:v3
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: config-tasks
          volumeMounts:
            - mountPath: /app
              name: project
      volumes:
        - name: project
          hostPath: 
            path: /root/gestion-de-tareas
            type: Directory

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-tasks
  namespace: tasks-namespace
spec:
  selector:
    matchLabels:
      app: mysql-tasks
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-tasks
    spec:
      containers:
        - name: mysql-tasks
          image: mysql:8
          ports:
            - containerPort: 3306
              name: web
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: tasksdb