apiVersion: v1
kind: Service
metadata:
  name: api-tasks
  namespace: tasks-namespace
spec:
  type: NodePort
  selector:
    app: api-tasks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30301
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-tasks
  namespace: tasks-namespace
spec:
  type: NodePort
  selector:
    app: mysql-tasks
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30201
