version : "3.5"
services:
  mysql:
    image: mysql:8
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234 
      - MYSQL_DATABASE=tasksdb
    volumes:
      - "./mysql:/var/lib/mysql"